import React, { useState } from 'react';
import { MOCK_BOOKS } from '../../constants';
import { generateDebate } from '../../services/geminiService';
import Loader from '../UI/Loader';

export const DebateArena: React.FC = () => {
  const [entityA, setEntityA] = useState('');
  const [entityB, setEntityB] = useState('');
  const [topic, setTopic] = useState('');
  const [loading, setLoading] = useState(false);
  const [debateScript, setDebateScript] = useState<{speaker: string, text: string}[]>([]);

  const handleDebate = async () => {
    if (!entityA || !entityB || !topic) return;
    setLoading(true);
    setDebateScript([]);
    
    // Simulate thinking delay for effect or just go straight to API
    const result = await generateDebate(entityA, entityB, topic);
    setDebateScript(result);
    setLoading(false);
  };

  return (
    <div className="max-w-5xl mx-auto animate-fade-in pb-20">
      <div className="mb-8 text-center">
        <h2 className="text-3xl font-bold text-gray-900 mb-2 font-serif">The Syntopicon Debate Arena</h2>
        <p className="text-gray-600">Synthesize knowledge by pitting two great minds against each other.</p>
      </div>

      <div className="glass-panel p-6 rounded-2xl shadow-xl mb-8">
        <div className="grid grid-cols-1 md:grid-cols-7 gap-4 items-end">
          
          {/* Entity A */}
          <div className="md:col-span-2">
             <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Contender A</label>
             <input 
               list="books" 
               type="text" 
               value={entityA}
               onChange={(e) => setEntityA(e.target.value)}
               placeholder="e.g. Einstein"
               className="w-full px-4 py-3 rounded-xl border border-indigo-200 focus:ring-2 focus:ring-indigo-500 bg-white"
             />
          </div>

          <div className="md:col-span-1 flex justify-center pb-3">
             <span className="font-serif font-bold text-2xl text-gray-400 italic">VS</span>
          </div>

          {/* Entity B */}
          <div className="md:col-span-2">
             <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Contender B</label>
             <input 
               list="books"
               type="text" 
               value={entityB}
               onChange={(e) => setEntityB(e.target.value)}
               placeholder="e.g. Newton"
               className="w-full px-4 py-3 rounded-xl border border-indigo-200 focus:ring-2 focus:ring-indigo-500 bg-white"
             />
          </div>

           {/* Topic */}
          <div className="md:col-span-2">
            <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Debate Topic</label>
            <input 
               type="text" 
               value={topic}
               onChange={(e) => setTopic(e.target.value)}
               placeholder="e.g. Nature of Gravity"
               className="w-full px-4 py-3 rounded-xl border border-indigo-200 focus:ring-2 focus:ring-indigo-500 bg-white"
             />
          </div>
        </div>
        
        <datalist id="books">
          {MOCK_BOOKS.map(b => <option key={b.id} value={b.author} />)}
        </datalist>

        <button 
          onClick={handleDebate}
          disabled={loading || !entityA || !entityB || !topic}
          className="w-full mt-6 py-4 bg-gray-900 text-white font-bold rounded-xl shadow-lg hover:shadow-xl hover:bg-black transition-all disabled:opacity-70"
        >
          {loading ? 'Simulating Discourse...' : 'Begin Debate'}
        </button>
      </div>

      {/* Arena Output */}
      <div className="space-y-6">
        {debateScript.map((turn, idx) => {
          const isA = turn.speaker.toLowerCase().includes(entityA.toLowerCase());
          return (
            <div 
              key={idx} 
              className={`flex ${isA ? 'justify-start' : 'justify-end'} animate-fade-in`}
              style={{ animationDelay: `${idx * 0.2}s` }}
            >
              <div 
                className={`max-w-[80%] p-6 rounded-2xl shadow-sm border ${
                  isA 
                  ? 'bg-white rounded-bl-none border-indigo-100' 
                  : 'bg-indigo-50 rounded-br-none border-indigo-200'
                }`}
              >
                <p className="text-xs font-bold text-indigo-600 mb-1 uppercase tracking-wider">{turn.speaker}</p>
                <p className="text-gray-800 leading-relaxed font-serif text-lg">{turn.text}</p>
              </div>
            </div>
          );
        })}
        
        {debateScript.length > 0 && (
           <div className="text-center pt-8 animate-fade-in" style={{ animationDelay: '2s' }}>
             <p className="text-gray-500 text-sm italic">Analysis generated by AI. Historical accuracy may vary.</p>
           </div>
        )}
        
        {loading && (
           <div className="flex flex-col items-center justify-center py-12">
              <div className="mb-8"><Loader /></div>
              <p className="text-indigo-800 font-medium">Analyzing philosophies...</p>
           </div>
        )}
      </div>
    </div>
  );
};